name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: npm install

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: |
          sudo apt-get install -y dos2unix
          dos2unix android/gradlew
          chmod +x android/gradlew

      - name: Build Android Release APK
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: |
          cd android
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          ./gradlew assembleRelease --stacktrace --info > gradle_build.log 2>&1

      - name: Upload Build Logs (If Failed)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: android/gradle_build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
